### ISSUE TITLE
rate limiting /throttling for API users

### ISSUE THREAD

**Issue by bedah-kym** [EduPapersKe/EduPapersAPI#60]
To prevent misuse of the resource a rate-limiting logic should be added so each user/client making API requests is limited to a certain number of requests a day.

**Comment by mwangi-brian** [comment]
Think about it @bedah-kym; if each client app were limited to like say 100 calls daily or any for that matter, that would mean that the client app would not be accessible all the time. Since this is not an API we're offering in return for any monetary benefit, that does not make sense here.

Can we agree on that?

**Comment by bedah-kym** [comment]
I agree with you, thanks for the point. The API should be fully accessible
at all times, we should be active on whatsapp so we can get our thoughts in
sync as a team.
